[package]
name = "l4re"
version = "0.1.0"
authors = ["Sebastian Humenda <shumenda @ gmx . de>"]
edition = "2018"

[lib]
path = "lib.rs"

[build-dependencies]
bindgen = "0.59.1"

[dependencies]
#libc = "0.2.43"
libc = { git = "https://github.com/Steav005/libc"}

[features]
default = []
