[package]
name = "shm_rust-client"
version = "0.1.0"
authors = ["streicher <shumenda@gmx.de>"]
edition = "2018"

[[bin]]
name = "shm_rust-client"
path = "client.rs"

[dependencies]
#libc = "0.2.43"
libc = { git = "https://github.com/Steav005/libc"}
