[package]
name = "basic_ipc"
version = "0.1.0"
authors = ["streicher <shumenda@gmx.de>"]

[[bin]]
name = "basic_ipc"
path = "main.rs"

[dependencies]
libc = { git = "https://github.com/rust-lang/libc" }
