[package]
name = "bench2-client"
version = "0.1.0"
authors = ["Sebastian Humenda <shumenda@gmx.de>"]
edition = "2018"

[[bin]]
name = "bench2-client"
path = "main.rs"

[dependencies]

[features]
default = ["test_string"]
test_string = []
